resources:
  - name:       Git
    type:       GitRepo
    configuration:
      gitProvider:  github-disha
      repository:   github-disha
      path:         dishameswania/project-examples
    buildOn:
      commit: true     

pipelines:
  - name: pipe1
    steps:
    - name: try1
      type: Bash
            
      execution:
          onStart:
            - echo "Prepping build environment"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff."
          onCancel:
            - echo "Someone cancelled the job."
