name: Maven Build and Publish

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Clean Maven settings to avoid conflicts
        run: |
          mkdir -p ~/.m2
          if [ -f ~/.m2/settings.xml ]; then
            rm ~/.m2/settings.xml
          fi

      - name: Setup JFrog Fly
        uses: jfrog/fly-action@v1
        with:
          url: https://supportfly.jfrog.io

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        working-directory: maven-examples/maven-example
        run: mvn -B -ntp -DskipTests package

      - name: Deploy (publish)
        if: github.event_name != 'pull_request'
        working-directory: maven-examples/maven-example
        run: mvn -B -ntp -DskipTests deploy


